[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "16.14.0"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
